use anyhow::Result;
use crate::api::GithubClient;
use crate::score::Scorer;

pub async fn run_export(
    username: &str,
    token: Option<String>,
    format: &str,
    output: Option<String>,
) -> Result<()> {
    eprintln!("Fetching data for {}...", username);
    let client = GithubClient::new(token);
    let data = client.fetch_all(username).await?;
    let scorer = Scorer::new();
    let report = scorer.compute(&data);

    let content = match format {
        "json" => export_json(&data, &report)?,
        "md" | "markdown" => export_markdown(&data, &report),
        other => anyhow::bail!("Unknown format: {}. Use json or md", other),
    };

    match output {
        Some(path) => std::fs::write(&path, &content)
            .map(|_| eprintln!("Report written to {}", path))?,
        None => print!("{}", content),
    }

    Ok(())
}

fn export_json(
    data: &crate::api::GithubData,
    report: &crate::score::ProfileScore,
) -> Result<String> {
    let combined = serde_json::json!({
        "generated_at": data.fetched_at,
        "profile": {
            "username": data.user.login,
            "name": data.user.name,
            "bio": data.user.bio,
            "followers": data.user.followers,
            "following": data.user.following,
            "public_repos": data.user.public_repos,
            "total_stars": data.total_stars,
            "total_forks": data.total_forks,
        },
        "health_score": report.overall,
        "avg_repo_score": report.avg_repo_score,
        "top_repos": report.top_repos,
        "repo_scores": report.repo_scores,
        "recommendations": report.all_recommendations,
    });
    Ok(serde_json::to_string_pretty(&combined)?)
}

fn export_markdown(
    data: &crate::api::GithubData,
    report: &crate::score::ProfileScore,
) -> String {
    let u = &data.user;
    let grade = match report.overall {
        90..=100 => "S", 80..=89 => "A", 70..=79 => "B",
        60..=69 => "C", 50..=59 => "D", _ => "F",
    };

    let mut md = format!(
        "# GitPulse Report — @{}\n\n\
        > Generated by [GitPulse](https://github.com/yourusername/gitpulse) on {}\n\n\
        ## 📊 Developer Health Score\n\n\
        **{}/100** (Grade: **{}**)\n\n\
        | Metric | Value |\n\
        |--------|-------|\n\
        | Overall Score | {}/100 |\n\
        | Avg Repo Score | {}/100 |\n\
        | Total Stars ⭐ | {} |\n\
        | Total Forks 🍴 | {} |\n\
        | Public Repos | {} |\n\
        | Followers | {} |\n\n",
        u.login,
        data.fetched_at.format("%Y-%m-%d"),
        report.overall, grade,
        report.overall,
        report.avg_repo_score,
        data.total_stars,
        data.total_forks,
        u.public_repos,
        u.followers,
    );

    md.push_str("## 🏆 Top Repositories\n\n");
    for rs in report.repo_scores.iter().take(10) {
        let bar = score_bar(rs.score);
        md.push_str(&format!("### {} — {}/100\n\n{}\n\n", rs.repo_name, rs.score, bar));
        md.push_str("| Check | Points |\n|-------|--------|\n");
        for item in &rs.breakdown {
            let icon = if item.passed { "✅" } else { "❌" };
            md.push_str(&format!("| {} {} | {}/{} |\n", icon, item.label, item.points, item.max_points));
        }
        md.push('\n');
    }

    md.push_str("## 💡 Top Recommendations\n\n");
    for rec in report.all_recommendations.iter().take(20) {
        md.push_str(&format!("- {} {} *(+{} pts)*\n", rec.severity.icon(), rec.message, rec.impact));
    }

    md.push_str("\n---\n*Generated with [GitPulse](https://github.com/yourusername/gitpulse)*\n");
    md
}

fn score_bar(score: u8) -> String {
    let filled = (score as usize * 20 / 100).min(20);
    let empty = 20 - filled;
    format!("`[{}{}]` {}%", "█".repeat(filled), "░".repeat(empty), score)
}

pub async fn generate_badge(username: &str, token: Option<String>) -> Result<()> {
    eprintln!("Fetching data for {}...", username);
    let client = GithubClient::new(token);
    let data = client.fetch_all(username).await?;
    let scorer = Scorer::new();
    let report = scorer.compute(&data);

    let score = report.overall;
    let color = match score {
        90..=100 => "brightgreen",
        70..=89 => "green",
        50..=69 => "yellow",
        30..=49 => "orange",
        _ => "red",
    };

    let badge_url = format!(
        "https://img.shields.io/badge/GitPulse%20Score-{score}%2F100-{color}?style=flat-square&logo=github"
    );

    println!("Badge URL:\n{}", badge_url);
    println!("\nMarkdown:\n![GitPulse Score]({})", badge_url);
    println!("\nHTML:\n<img src=\"{}\" alt=\"GitPulse Score {}/100\">", badge_url, score);

    Ok(())
}
